project:
  type: book

book:
  title: "3rd Year Report"
  author: "Susana Roman Garcia"
  date: now
  date-format: long
  chapters:
    - index.qmd
    - 10-involvement.qmd
    - 20-enrichment.md
    - 30-quarto_thesis.md
    - references.qmd

bibliography: 
- references.bib
link-citations: true

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
        
execute:
  freeze: auto


