project:
  type: book

book:
  title: "3rd Year Report"
  author: "Susana Roman Garcia"
  date: now
  date-format: long
  chapters:
    - index.qmd
    - 10-whatsmyphd.md
    - 20-ethics_reproducible.md
    - 30-data_hazards.qmd
    - 40-models.qmd
    - 50-activities.md
    - 60-thesis_layout.md
    - references.qmd

  repo-url: https://github.com/Susana465/third_year_report
  downloads: [pdf]
  page-navigation: true

bibliography: 
- references.bib
link-citations: true

format:
  html:
    theme: pulse
    mermaid: 
      theme: forest
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
        
execute:
  freeze: auto # Re-compute previously generated computational output only in case their source file changes
  echo: false # do not include source code in output


